# This is a basic workflow to help you get started with Actions

name: Bun Check rimraf

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - fe-develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 5
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Base ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: fe-develop

      - name: Npm Install ğŸ›ï¸
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Bun Install ğŸ›ï¸
        uses: oven-sh/setup-bun@v2

      - name: Bun Run ğŸ›ï¸
        run: |
          mkdir rimraf-test
          cd rimraf-test

          npm init -f -y
          bun install --save-dev rimraf
          bun run rimraf:non-exist
        working-directory: PreciseAlloy.Frontend
